do $$ begin create role anon nologin; exception when duplicate_object then null; end $$; do $$ begin create role authenticated nologin; exception when duplicate_object then null; end $$;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
grant usage on schema auth to anon, authenticated; grant usage on schema public to anon, authenticated;
create table companies(id uuid primary key default gen_random_uuid(), name text);
create table users(id uuid primary key, email text, name text, company_id uuid, status text, approved_by uuid, approved_at timestamptz);
create table permissions(code text primary key, name text);
create table clubs(id uuid primary key default gen_random_uuid(), name text, description text, status text default 'active', cover_image_url text);
create table user_permissions(id uuid primary key default gen_random_uuid(), user_id uuid, permission_code text, club_id uuid, company_id uuid, granted_by uuid);
create table club_members(id uuid primary key default gen_random_uuid(), club_id uuid, user_id uuid, role_label text, status text, withdrawal_requested boolean default false, processed_by uuid, processed_at timestamptz);
create table club_lifecycle_requests(id uuid primary key default gen_random_uuid(), type text, club_id uuid, requester_id uuid, status text, proposed_name text);
create table club_support_rates(id uuid primary key default gen_random_uuid(), club_id uuid, unit_amount int);
create table posts(id uuid primary key default gen_random_uuid(), club_id uuid, author_id uuid, type text, title text);
create table post_attachments(id uuid primary key default gen_random_uuid(), post_id uuid, file_url text);
create table post_attendees(post_id uuid, user_id uuid);
create table post_comments(id uuid primary key default gen_random_uuid(), post_id uuid, author_id uuid, content text);
create table post_likes(post_id uuid, user_id uuid);
create table club_budget_disbursements(id uuid primary key default gen_random_uuid(), club_id uuid, company_id uuid, status text);
grant select,insert,update,delete on all tables in schema public to anon, authenticated;
